### ISSUE TITLE
Original contours are quadratic (TrueType)

### ISSUE THREAD

**Issue by alexeiva** [alexeiva/Istok-Web#1]
Original author Andrey V. Panov designed Istok fonts in FontForge in quadratic contours from the outset. He wrote:

> This was done to control the numbering of the nodes, and facilitate further hinting instructions. Althought, it was much harder to design.

Here is glyph `infinity` after converting from quadratic to cubic outlines in FontForge.

<img width="745" alt="screen shot 2016-09-08 at 12 07 41" src="https://cloud.githubusercontent.com/assets/16634089/18669174/f3156a78-7f39-11e6-9dd2-15065a2aa533.png">

As part of cleanup/expansion the SFD was later exported to OTF, and opened in Glyphs:
<img width="722" alt="screen shot 2016-09-08 at 11 55 03" src="https://cloud.githubusercontent.com/assets/16634089/18669175/f40db476-7f39-11e6-9961-1fbbe46c0f0f.png">

Since existing hinting would be dropped, and re-hinted with ttfautohint, maintaining TT contours isn't viable anymore.  

I did not find a solution to automate contour conversion with adequate quality. 

@m4rc1e any thought on this?

A better way to convert the sources would be via `SFD2UFO`, but on my part it created multiple errors, that I could not tackle.

**Comment by m4rc1e** [comment]
hey @alexeiva,

Since quad curves are the source, your best bet is to open the ttfs in Fontlab then convert 
![screen shot 2016-09-21 at 11 55 24](https://cloud.githubusercontent.com/assets/7525512/18706467/6b5611c8-7ff2-11e6-954d-410547368bf8.png)


![screen shot 2016-09-21 at 11 55 35](https://cloud.githubusercontent.com/assets/7525512/18706457/5f06e0f0-7ff2-11e6-912d-5e5d98fa2ec4.png)

There should be little distortion with this approach. Again you'll end up with more points, just delete the extras points if you actually work on the glyph.

Cheers,
Marc

**Comment by m4rc1e** [comment]
![screen shot 2016-09-21 at 12 00 56](https://cloud.githubusercontent.com/assets/7525512/18706629/13f51d24-7ff3-11e6-90e5-278b05e8a8de.png)

**Comment by alexeiva** [comment]
@m4rc1e 
I agree. That's the best solution. Thank you for this

**Comment by alexeiva** [comment]
fixed in 9484ac75434bfb64641855d151d44e247a2a893c
